### ISSUE TITLE
cross_line_String line_no problem

### ISSUE THREAD

**Issue by enewen0324** [ICD20/hw1#13]
String.p
![image](https://user-images.githubusercontent.com/55022091/93856490-ac82f880-fceb-11ea-8a60-b0c47bbff7f7.png)

answer/String.out
![image](https://user-images.githubusercontent.com/55022091/93856555-bd336e80-fceb-11ea-82b4-d67ee2cbdf5c.png)

為什麼String.out的line_no是10、12、14呢?
```
  10-th token(type:STRING    ) on line   10,   1 : " Multi-Line
  String Can you tokenize it"
  11-th token(type:STRING    ) on line   12,   1 : " Multi-Line
  With comment // This is a comment "
  12-th token(type:STRING    ) on line   14,   1 : " Multi-Line
  With comment 
```
因為col是1所以應該是在line_no 9、11、13?
還是我對line_no跟col誤會了?

**Comment by nobodyzxc** [comment]
我們這邊的範例程式有問題，是 9, 11, 13 沒錯，
這邊會盡快修正測資，謝謝回報。
