### ISSUE TITLE
WSL 2 installation is incomplete

### ISSUE THREAD

**Issue by nsyolin** [ICD20/hw1#14]
照著指示安'裝完也沒用。
![image](https://user-images.githubusercontent.com/71622480/93868333-e6a8c600-fcfc-11ea-8b17-5fa9d835cd9a.png)

**Comment by nobodyzxc** [comment]
請問是新機器嗎？
在前一個 issue 我看你應該是可以用了，你是開啟 Docker Desktop 做更新嗎？

**Comment by nsyolin** [comment]
是的 新機器

**Comment by nobodyzxc** [comment]
不好意思，有點晚回覆。
請問[這篇](https://stackoverflow.com/questions/63845591/docker-wsl-2-installation-is-incomplete) 可以幫助到你嗎？
如果不行的話，可能要先請你找其他環境寫，
可以上計中直接寫，最好切到 bash，因為有同學反應 tcsh 的資料流重導向可能有問題，或者直接用 makefile 做 diff。
或者是可以在計中上使用 docker，詳情請閱 READEME.md 。

**Comment by nsyolin** [comment]
解決了 謝謝
