### ISSUE TITLE
On the separation of REALNUMBER, INTEGERNUM, and SCIENTIFIC tokens

### ISSUE THREAD

**Issue by abt8601** [ICD20/hw1#16]
在新的 template 裡面有以下3個分開的 token

https://github.com/ICD20/hw1/blob/8771c14bf59c616f1e262dab4fe3ac9c74cd5f21/scanner.l#L53-L55

而 `01-minipascal-spec.pdf` 的第1頁提到

> `num` is the token for all numbers, such as 3.14, -999, +123, 2.71, etc. You need to define scientific notation such as 2.503E-7 as a `num` token. You need to define a reasonable expression for `num`, such as 123, -34.764, 2.53E+24, +0.001E21, 99.456E-12, etc.

請問本次作業需要遵照哪一個規範？（若不考慮往後的作業，並且在 scanner 的輸出都完全正確的前提下）

**Comment by rniczh** [comment]
因為不允許浮點數和整數的加法計算...etc，所以你必須要做檢查，有兩個方式下手，syntax 上面就禁止這件事情發生(syntax analysis)，這樣做的話就是給他不同的 token type，不過以 spec 來說，就是在 semantic analysis 在做這件事情。你可以參考普遍 C 語言編譯器在 number casting 的方式來了解。reference book：A retargetable c compiler

**Comment by nobodyzxc** [comment]
Token 要不要分開其實都可以，
只是輸出為 NUMBER 對大家比較寬鬆。
這邊給大家實作的空間，
之後 parser 只要符合 grammar 需求，
都可以照自己需求調整 synatx。
