### ISSUE TITLE
Handle printf buffer

### ISSUE THREAD

**Issue by homeworksuck** [ICD20/hw1#17]
助教您好
1. 我的output資料夾中的輸出檔因為printf的buffer size關係，導致格式有誤差(printf的buffer滿了就輸出，導致跟fprintf的stderr衝)，使的比較大的testcase都是錯的，因為type跟list交互出現。我們需要自己去處理這個狀況嗎?
2. 輸出格式是要用\r\n還是\n?

**Comment by nobodyzxc** [comment]
會混起來應該是正常的，
答案的 source code 和 token 會分開是因為我們在 Makefile 裡面有作重導向。
所以應該不是 buffer 的問題。

輸出統一用 \n，你可以用 `make test` 來直接比對參考輸出和你的輸出。

**Comment by nobodyzxc** [comment]
感謝回報，
我們把 token 和 source code 改成分別輸出，應該就沒這個問題了。
至於 \r\n 的部份我在 diff 那邊加了一個 `--strip-trailing-cr` 應該會有用，就麻煩你再測試一下了。
