### ISSUE TITLE
cannot install docker on linux

### ISSUE THREAD

**Issue by nsyolin** [ICD20/hw1#18]
https://docs.docker.com/engine/install/ubuntu/
照著這個網站做 中間就跳出錯誤
![Screenshot from 2020-09-25 03-45-37](https://user-images.githubusercontent.com/71622480/94258429-69c95680-ff5f-11ea-96a2-490a60bd4e92.png)

**Comment by nobodyzxc** [comment]
前面的 apt-get 操作應該都要加上 sudo
```
$ sudo apt-get update

$ sudo apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common
```

**Comment by nsyolin** [comment]
![image](https://user-images.githubusercontent.com/71622480/94260024-07be2080-ff62-11ea-8cfa-0592b49d3098.png)
這段直接打就好嗎?

**Comment by nobodyzxc** [comment]
不是 你那段是要驗證 curl 有沒有成功，不用打你框起來的部份。
![image](https://user-images.githubusercontent.com/17202064/94262034-5faa5680-ff65-11ea-9580-1b4bc70b98d2.png)
像是我還沒 curl，直接下 fingerprint 他會沒東西，
下了  curl 後，fingerprint 才有結果。

**Comment by nsyolin** [comment]
![image](https://user-images.githubusercontent.com/71622480/94265800-c0d52880-ff6b-11ea-968a-2587ba415eaf.png)
這段是要全部打嗎?

**Comment by nobodyzxc** [comment]
請參考當初信件內容，或者是剛更新的 README.md Ubuntu 安裝方法，
其實只要四個指令就可以裝好了。
```bash
sudo apt install docker.io

sudo systemctl start docker
sudo systemctl enable docker

sudo usermod -aG docker $USER

# and re-login the system
```

**Comment by nsyolin** [comment]
![Screenshot from 2020-09-25 05-39-58](https://user-images.githubusercontent.com/71622480/94268196-61791780-ff6f-11ea-924e-6ca19634e605.png)
這樣就可以了嗎?

**Comment by rniczh** [comment]
是的，你可以 clone repo 下來試試看可不可以用課程提供的 image

**Comment by nobodyzxc** [comment]
> ![Screenshot from 2020-09-25 05-39-58](https://user-images.githubusercontent.com/71622480/94268196-61791780-ff6f-11ea-924e-6ca19634e605.png)
> 這樣就可以了嗎?

看起來不太像，你這是啥 command 的 help？

**Comment by nsyolin** [comment]
sudo apt install docker.io

sudo systemctl start docker
sudo systemctl enable docker

sudo usermod -aG docker $USER
這四個做完

**Comment by nsyolin** [comment]
![Screenshot from 2020-09-25 06-07-23](https://user-images.githubusercontent.com/71622480/94270772-31337800-ff73-11ea-870c-8d76ae1ababd.png)
clone會放在哪裡呢?

**Comment by nobodyzxc** [comment]
當前目錄會多出個 hw1，進去 然後 bash activate.sh

**Comment by nsyolin** [comment]
![Screenshot from 2020-09-25 06-11-14](https://user-images.githubusercontent.com/71622480/94271109-bf0f6300-ff73-11ea-9391-5e9485bba078.png)
打那串 bash activate.sh嗎?

**Comment by nobodyzxc** [comment]
對

**Comment by nsyolin** [comment]
![Screenshot from 2020-09-25 06-19-36](https://user-images.githubusercontent.com/71622480/94271891-de5ac000-ff74-11ea-8988-811a59b56a20.png)
甚麼都沒發生

**Comment by nobodyzxc** [comment]
你現在在編輯器裡面，請把剛剛打的 bash activate.sh 刪掉，然後退出。
接著在 shell 裡面 bash activate.sh。

**Comment by nsyolin** [comment]
![Screenshot from 2020-09-25 06-31-01](https://user-images.githubusercontent.com/71622480/94273024-760cde00-ff76-11ea-8af3-c327b24e0eca.png)
是這個嗎?  我不知道怎樣進shell

**Comment by nobodyzxc** [comment]
就是你剛剛打 apt-get 那些 command 的地方

**Comment by rniczh** [comment]
`c-x c-c` (ctrl + x, ctrl + c) 離開 emacs

左邊列表上面有個 terminal 的圖案那個，進去就是 shell 了

**Comment by nsyolin** [comment]
![Screenshot from 2020-09-25 06-34-46](https://user-images.githubusercontent.com/71622480/94273419-fb908e00-ff76-11ea-960a-be6ee8654305.png)
no such file

**Comment by nobodyzxc** [comment]
```
cd hw1
bash activate.sh
```

**Comment by nsyolin** [comment]
![Screenshot from 2020-09-25 06-38-30](https://user-images.githubusercontent.com/71622480/94273829-82de0180-ff77-11ea-8a39-b3a9885c24f0.png)
可以了 然後要改作業的哪裡呢?

**Comment by nobodyzxc** [comment]
同學，我們還是約個 ta time 吧，看起來你對 Ubuntu 好像也不太熟。
請問你有時間，然後方便帶個筆電之類的嗎？我們用 E3 發信件約個時間吧！

**Comment by nsyolin** [comment]
我有發信了 請助教回復 謝謝 會帶筆電

**Comment by nobodyzxc** [comment]
是約明天的同學嗎？

**Comment by nsyolin** [comment]
是的
