### ISSUE TITLE
Multiple line string

### ISSUE THREAD

**Issue by Platisenic** [ICD20/hw1#19]
![擷取](https://user-images.githubusercontent.com/69299037/94346177-7a5ff680-005d-11eb-8ec0-63b337fbdf3b.JPG)

助教您好:
在01-minipascal-spec.pdf 中有說string不能跨行
但是在測資中有跨行且token為string的情形

**Comment by nobodyzxc** [comment]
Thanks for reporting, 
we will update the data as soon as possible.
