### ISSUE TITLE
NUM token

### ISSUE THREAD

**Issue by Ligoon** [ICD20/hw1#20]
助教好：請問如果有正負號在 number 前面需要歸類成 number 還是 keyword+number？例如 1+-5，可以把'+'跟'-'都認定成 keyword 嗎？還是說 '+' 為 keyword 然後 '-5' 為 number？感覺前者在實作起來比較簡單，但不是很確定這樣進到 parser 的時候會不會出錯。但如果要按照 spec 似乎就要用後者的方式？
<br>
![擷取](https://user-images.githubusercontent.com/41354176/94358203-ebd98c80-00d1-11eb-829b-befd4ce13563.JPG)

**Comment by rniczh** [comment]
如果是前者，到 parser 時只要注意一下優先級，如果以課程來說會是採用 yacc ，那可能 `%prec` 就能解決了，不太會有什麼問題。

@nobodyzxc spec 這樣寫的話... 🤨 我是很想要直接用前者來解決啦。

**Comment by nobodyzxc** [comment]
![image](https://user-images.githubusercontent.com/17202064/94362282-d6be2700-00ec-11eb-82fb-1f2135ed156d.png)
老師之前公告，已經有寄信通知不用 handle signed number，所以之後測資應該不會出現 singed number，
我目前是覺得 scanner 都把 [+-] 當作 keyword token，到 parser 再讓他 reject 掉？
