### ISSUE TITLE
Problem in downloading docker

### ISSUE THREAD

**Issue by sugaarrrr** [ICD20/hw1#21]
助教們您好,

當我安裝docker時, 碰到了這個問題. 請問一下此如何解決呢? 謝謝您!

![image](https://user-images.githubusercontent.com/55147734/94368783-b1471280-0118-11eb-8da9-eecc6a0b06d7.png)

**Comment by nobodyzxc** [comment]
已經更新 activate.bat 了，你拉下來再試試看，
主要應該是 path 的問題，把 `%cd` 改成 `"%cd%"`，
不過我們手邊沒機器可以測試，就請你那邊測試看看，謝謝。

**Comment by sugaarrrr** [comment]
結果還是一樣.... 
![image](https://user-images.githubusercontent.com/55147734/94370534-32a3a280-0123-11eb-8113-404d2b0055a6.png)

**Comment by nobodyzxc** [comment]
抱歉，我剛剛才發現我忘了 push，
你測的時候順便檢查一下 bat 裡面有沒有加 double quote，謝謝。

**Comment by nobodyzxc** [comment]
@sugaarrrr 請問問題解決了嗎？
如果解決了麻煩直接 close 這個 issue，謝謝。
