### ISSUE TITLE
download docker in windows 7

### ISSUE THREAD

**Issue by laiyousin** [ICD20/hw1#22]
助教您好，想請問以下兩個問題：
1.
![執行此command才能正確執行](https://user-images.githubusercontent.com/68462169/94508107-cb314400-0243-11eb-925e-a7cc860a8783.PNG)
每次重開cmd都需執行docker-machine env default指令才能正確執行
2.
![activate的問題](https://user-images.githubusercontent.com/68462169/94508214-0b90c200-0244-11eb-973e-20442785ea25.PNG)
執行activate.bat後，會出現此error
想請問有何方法可以解決？
麻煩助教了!

**Comment by nobodyzxc** [comment]
看起來 win7 的 docker 支援並不是很好，
要分享資料夾有點麻煩，首先要用 virtual box share directory，
然後用 cygwin linux style 的 path (用 //c 或 //d 開頭)。

看來有點麻煩，這邊建議環境可以直接使用 README.md 更新的 MobaXterm 的使用說明。
至於 docker 測試，你可以在 code 完成後再上去 cc workstation 測一下。

**Comment by laiyousin** [comment]
好的!謝謝助教~
