### ISSUE TITLE
coding pattern

### ISSUE THREAD

**Issue by sugaarrrr** [ICD20/hw1#26]
助教好,

想問一下我們必要跟著助教提供給我們那個code的格式 (像SAMPLE1-standard-pascal-no-yacc.l ) 來寫此作業的code, 還是我們可以隨意修改那個code或用自己的寫法來寫作業?
謝謝.

**Comment by nobodyzxc** [comment]
當然是不用的，但就是照 spec 要求實作，然後通過 test case 就好。
但這個作業是希望你用 lex，如果自己造一個字串處理的程式，沒用到 lex，我們大概也會有點為難。
