### ISSUE TITLE
output format

### ISSUE THREAD

**Issue by sugaarrrr** [ICD20/hw1#27]
助教好,

請問, 那個輸出的格式我們需不需要管在  " (type:TOKEN   ) 裡面的那個whitespace嗎？（像下面照片的那個紅色標記)
![4C8F8DAA-2F02-4550-AB2D-A7F17C6B5A9C](https://user-images.githubusercontent.com/55147734/94760587-850bea00-03d5-11eb-8877-0a557262be2e.jpg)

**Comment by rniczh** [comment]
test 會檢查到，那邊是固定長度的，你可以參考一下我們提供的 scanner.l 下面輸出的部分。
