### ISSUE TITLE
String token

### ISSUE THREAD

**Issue by Ligoon** [ICD20/hw1#28]
想請問：
1. 如果遇到 `"alpha\"beta"` 或 `"good\\bad\\ugly"` 這種 string，在處理及 output 的時候需要改成 `"alpha"beta"` 及 `"good\bad\ugly"` 嗎？
2. 如果遇到 \n、\0、\t 等跳脫字元，如：`"abc\ndef"` 在測資中是直接當作 string 處理，那之後實際換行(\n)的時候是會到 parser 才會處理嗎？
3. 想問一下這句：However, you may even build a library for functions related to strings (for extra points). 是甚麼意思？
<br>

![擷取](https://user-images.githubusercontent.com/41354176/94769079-c4d9ce00-03e3-11eb-86eb-4a466fd1d2fa.JPG)

**Comment by nobodyzxc** [comment]
1. 輸出直接用 yytext 輸出就好，scanner 這邊還不用做任何修改，
處理資料型態轉換應該是 parser 要考慮的事情。
2. 對的，同上，你現在只要符合參考輸出就行了。
3. 之後可能會把字串串接等函數實作當作加分題。
