### ISSUE TITLE
Leading zeros in NUMBER token

### ISSUE THREAD

**Issue by Ligoon** [ICD20/hw1#29]
想請問關於 number 的定義
1. 在 spec 裡面似乎沒有很明確的定義 00 或 00123 的行為，但在測資答案中把 00 跟 00123 都當作 NUMBER token，這樣是正確的嗎？還是要當做三個 integer token : 0、0、123
2. `a := 00` 跟 `a := 00123` 在未來整個 compiler 中會被當作合法的輸入嗎？在 python 中前者是合法的但後者會被當作 invalid token
3. 如果 `00123` 在 scanner 是被當作一個 integer token，那也是在 parser 才會做進一步的 invalid/valid 判斷嗎？

![擷取](https://user-images.githubusercontent.com/41354176/94795593-2021b580-0410-11eb-9729-3dd71fdbb7a2.JPG)

**Comment by nobodyzxc** [comment]
1. 因為 spec 目前沒有定義沒錯，所以我們目前就允許 leading zero 當作合法輸入，作為一個 token，應該對大家也易於實作。
2. 應該是會當作合法輸入的，其實 leading zero 在每個語言的語義都會有點不同，像 C 就會把他當作八進制，不過 mini pascal 沒有設計進制，語義上就是單純忽略 leading zero 而已。
3. 之後 parser 應該會直接 ignore leading zero，所以應該不會去 reject 他。
