### ISSUE TITLE
First character in an Identifier

### ISSUE THREAD

**Issue by sugaarrrr** [ICD20/hw1#31]
依照spec, 10.3EBC 是要把EBC歸類成 IDENTIFIER, 
![image](https://user-images.githubusercontent.com/55147734/94884737-d6cd7680-04a0-11eb-817f-40fbfc37a81d.png)

不過在answers,EBC 就是一個 lexical analyzer error. 
![image](https://user-images.githubusercontent.com/55147734/94884797-07adab80-04a1-11eb-9640-4fec342b1ca6.png)

助教們想問一下,　哪一個是正確的答案？

**Comment by rniczh** [comment]
看起來這個說明跟 spec 這段好像有衝突到，因為這段是寫 `a-z` 而沒包含了 `A-Z` 作為開頭。

![image](https://user-images.githubusercontent.com/4802296/94885842-f4500f80-04a3-11eb-8ae3-b230309e464b.png)

@nobodyzxc

**Comment by nobodyzxc** [comment]
對 有衝到 原則上還是照 spec 吧
不過其實限定小寫開頭我是覺得滿怪的
