### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by sugaarrrr** [ICD20/hw1#32]
助教好,

此次我就是測試Comments.p, 然後當我在cmd(docker)測試列印我code的結果時, 看來好像我輸出的答案是沒有錯的 , 不過假如我用make test 來測試的話, 就是一直incorrect. 想請問一下, 當我們處理那個comment時,有沒有像特別輸出列印的格式或規定之類, 還是之前有沒有類似的
問題這樣? 謝謝

![image](https://user-images.githubusercontent.com/55147734/94981201-b8c84a80-0562-11eb-8582-d5d86d7705a4.png)

**Comment by nobodyzxc** [comment]
可以用 diff 或是 vimdiff 之類的工具去比對檔案，
這樣可能比較好看。
另外我們有一筆測資有兩個東西要比，一個是輸出 token, 一個是輸出的 source code, 你要看一下是哪個不正確。
