### ISSUE TITLE
test-pragma-list.token.src

### ISSUE THREAD

**Issue by Platisenic** [ICD20/hw1#33]
助教好:
answers 中的 test-pragma-list.token.src 和 test-pragma-list.p 內容不同
似乎是 test-pragma-list.token.src 沒有更新到嗎
![擷取](https://user-images.githubusercontent.com/69299037/95011412-1348d000-0663-11eb-8951-833dbd3c0569.JPG)

**Comment by nobodyzxc** [comment]
因為 list off 會把 srouce code listing 關掉，
所以到下次 list on 之前那段會不顯示。

**Comment by Platisenic** [comment]
我瞭解了，謝謝助教
