### ISSUE TITLE
About Makefile: make run

### ISSUE THREAD

**Issue by sugaarrrr** [ICD20/hw1#35]
助教好，
想確認一下， 我們makefile的那個`make run `command需要我們compile到哪? 執行flex 跟gcc(像助教給的makefile的 `make` command)就可以了還是有需要執行到其他的file? 

![image](https://user-images.githubusercontent.com/55147734/95072286-8aeb2d80-073d-11eb-9239-6b74f46dcd85.png)

**Comment by rniczh** [comment]
please refer to #25 

不用 `make run` 這個就是目前的 `make`
