### ISSUE TITLE
.token incorrect & .token.src pass the test

### ISSUE THREAD

**Issue by laiyousin** [ICD20/hw1#36]
助教您好~
1.![通過](https://user-images.githubusercontent.com/68462169/95165462-95a9cf00-07de-11eb-8e86-d71bf067f8f7.PNG)
想請問為何有些.token錯誤，但.src卻可以通過？
2.使用mobaxterm要如何印出單獨test檔案的output？
謝謝助教!!

**Comment by rniczh** [comment]
1. .src 就只是有把 code 印出來，所以如果 NUMBER 被 lex 錯成 IDENTIFIER 這種事情就不會影響了，但會影響到 token

2. @nobodyzxc

**Comment by rniczh** [comment]
可以比較一下答案跟你輸出的結果，`diff test/output/Comments.token test/answers/Comments.token` 看哪行有錯

**Comment by nobodyzxc** [comment]
可以啊

**Comment by laiyousin** [comment]
了解了!!!謝謝助教~~
