### ISSUE TITLE
關於unicode replacement character比對問題

### ISSUE THREAD

**Issue by chenyus0609** [ICD20/hw1#37]
助教您好:
我在執行make test的結果發現output/scanner-test02-pragma.token is incorrect
但是經過diff比對後得到下面的資訊(見下圖):
![image](https://user-images.githubusercontent.com/48789942/95172073-651b6280-07e9-11eb-977f-61440a66ca63.png)

可以很明顯看到我的結果應該是與answer一致的，但是不論是diff或是make test都說我的output與answer有差異，請問這是unicode replacement character的編碼問題嗎? 我應該如何修正?

謝謝助教!

**Comment by rniczh** [comment]
你可以把你的 code 附件寄給我們，我再幫你看一下。

**Comment by nobodyzxc** [comment]
Column number 有錯

**Comment by rniczh** [comment]
你傳給我的 code 我跑過了，是沒問題的。但你這邊有顯示錯誤，奇怪

**Comment by chenyus0609** [comment]
@rniczh 助教那也就是說我全部測資在你那邊跑都是pass的這樣嗎XD

**Comment by rniczh** [comment]
@chenyus0609  是的，不過你的 `test/` 是最新的嗎？可以替換看看，然後 `make clean` 後再 `make test` 執行看看。
不過你傳給我的這份可以先上傳了。

**Comment by chenyus0609** [comment]
請問助教最新的`test/`是指e3上的`scantest-answer`嗎? 還是直接github上資料夾這邊的?

**Comment by rniczh** [comment]
@chenyus0609 Github 上這裡的。

**Comment by chenyus0609** [comment]
@rniczh 好的，另外我發現我用最新的`test`就不會有我一開始的問題，可以全部pass了，可能是我有動到甚麼東西，總之可以了，謝謝助教!
