### ISSUE TITLE
Lex string literals in block comments?

### ISSUE THREAD

**Issue by abt8601** [ICD20/hw1#38]
前陣子在其他專案翻到了這篇 issue ，是關於 block comment 和 string literal 之間的互動： https://github.com/agda/agda/issues/4953

請問在 minipascal 裡，分析 `/* "*/" */` 這段 code 的時候需要將 `"*/"` 全部算在 block comment 裡面，還是把引號中間的 `*/` 當作 block comment 的結束？ Test case 裡面似乎沒有針對這個 pattern 作測試。

**Comment by rniczh** [comment]
是的，沒有針對這種狀況處理，當做目前 C-style 的 comment 處理就行了。

**Comment by abt8601** [comment]
> 當做目前 C-style 的 comment 處理就行了

所以要把引號中間的 `*/` 當作 block comment 的結束嗎？（和 C 的行為相同）

**Comment by rniczh** [comment]
@abt8601 對的，不過這種寫法其實也蠻有趣的（e.g. ocaml )

**Comment by abt8601** [comment]
瞭解了，謝謝助教

話說會這樣做的語言（OCaml、Coq等等）很像都是INRIA做的 :laughing:
