### ISSUE TITLE
HW1補交

### ISSUE THREAD

**Issue by hikariksw** [ICD20/hw1#42]
助教好，我在10/9的時候有依據"Scanner Project評分標準"所指示的方式透過new e3平台的"我的郵件"系統補交作業，但目前還沒有得到回覆，想請問助教是否有收到我補交的檔案?謝謝助教。

**Comment by rniczh** [comment]
有的，只是預計是在補交時間結束後我們再一次處理並給予成績。

**Comment by hikariksw** [comment]
好的，謝謝助教
