### ISSUE TITLE
Question about  installing  docker

### ISSUE THREAD

**Issue by nsyolin** [ICD20/hw1#5]
照著yt的方法安裝到activate.bat這步時出現
![image](https://user-images.githubusercontent.com/71622480/93732744-399f5200-fc05-11ea-9010-889155ebe5ce.png)
請問該怎麼辦

**Comment by rniczh** [comment]
你試試看到 settings 裡面的 Resources 部分中的 File Sharing 加入你的 path，看能不能解決。

![image](https://user-images.githubusercontent.com/4802296/93742854-6f523400-fc21-11ea-8f13-8158691cc68c.png)

**Comment by nobodyzxc** [comment]
![](https://www.broispro.com/wp-content/uploads/2020/05/Docker-error-500-1.jpg)

reference: [500: {“Message”:”Unhandled exception: Filesharing has been cancelled}](https://www.broispro.com/2020/05/30/500-messageunhandled-exception-filesharing-has-been-cancelled/)

**Comment by nsyolin** [comment]
我make pack以後scanner.c檔就會不見
![image](https://user-images.githubusercontent.com/71622480/93778264-46996100-fc58-11ea-9b78-753e9685049e.png)
請問問題在哪裡呢?

**Comment by rniczh** [comment]
是的，make pack 會先執行 make clean 把不需要的東西刪掉後才打包，由於 `.c` 的檔案會在 make clean 後刪除，所以會看不到，你重新 `make` 後就會再產生了。

@nobodyzxc 你覺得需要改嗎？(e.g. ` find ... -exec zip ... ` 或是 zip 的 `--exclude`) ？ 我是覺得這樣就好了。

**Comment by nobodyzxc** [comment]
Makefile 裡面本來就有 ignore hidden file 和 test/* 了，
```
pack:
	make clean
	zip -r icd20-hw1.zip . -x ".*" -x "*.zip" -x "test/*"
```
因為還有些 object file 和 executable (no extension) 所以我才會用 make clean，要改成全用 ignore 嗎？
我是覺得 pack 已經是最後階段了，順便清一清，應該沒什麼影響。

**Comment by rniczh** [comment]
那就保留這樣吧
