### ISSUE TITLE
Is it necessary for installing docker?

### ISSUE THREAD

**Issue by Ligoon** [ICD20/hw1#6]
助教 請問這次作業有一定要用 docker 嗎？我目前是直接用系計中的 server，如果有 yacc 跟 flex 可以用，這樣還需要裝 docker 嗎？還是說在之後的作業有其他工具或環境需要用到的？
<br>
![擷取](https://user-images.githubusercontent.com/41354176/93751548-d70f7b80-fc2f-11ea-9fd8-11b356c36015.JPG)

**Comment by rniczh** [comment]
可以不用，除非你有安裝其他東西，像是你想要用 Haskell 來寫之後的作業的話，那可能就會需要麻煩你在 Makefile 中的 prepare 那邊搭配 docker image 環境來安裝相對應的 package。

我們需要你提供 makefile 並有下列幾項功能

1. makefile 中 `make` 必須產生 "scanner" 的 binary。
2. **在有自己安裝的 package 情況下**，沒有的可以略過這項，makefile 中 `make prepare` 必須寫上你下的安裝指令 (e.g. apt install g++) 並確保在 docker image 上可以執行

**Comment by rniczh** [comment]
@nobodyzxc what do you think ?

**Comment by nobodyzxc** [comment]
理論上計中的環境應該足以支持整個 project 的需要，
lex 和 yacc 應該也沒什麼跨平台的問題，但如果想要更確定 project 可以運行的話，
也可以在計中的 Linux 工作站（非 BSD）使用 docker。

他們提供了 dosh 這個 shell 來操作，相關用法我已經更新在 [README.md](https://github.com/ICD20/hw1/blob/master/README.md)

**Comment by abt8601** [comment]
> 你想要用 Haskell 來寫之後的作業的話

所以之後的作業可以用 Haskell 寫嗎？（除了 lex 和 yacc 的部分）

**Comment by nobodyzxc** [comment]
如果想用其他語言的建議一開始就使用該語言，
比如一開始就用 Haskell 的 lex 和 yacc，
因為一開始的部份就會影響到後面的實作了，
因為後面的 analysis 會使用到 lex 和 yacc 的結果，要怎麼傳遞是個問題。

如果想要嘗試起他語言實作，建議要有足夠熟悉度，
另外在 make prepare 要準備好安裝的工具，以便 docker container 安裝。
