### ISSUE TITLE
Hw1 Question

### ISSUE THREAD

**Issue by YJChen0208** [ICD20/hw1#7]
助教你好，

請問 id 可以用底線當開頭或結尾嗎？

10-scanner.pdf 內寫 id 用 a-z 當開頭，底線不能當結尾
![image](https://user-images.githubusercontent.com/45586059/93760751-33c66280-fc3f-11ea-964f-a8af955ddfbb.png)

但是 Identifier.out 內卻不同，要按照哪個呢？
![image](https://user-images.githubusercontent.com/45586059/93761093-c49d3e00-fc3f-11ea-9a7b-9f6ec8048644.png)

**Comment by rniczh** [comment]
看起來是以前測資遺留下來然後這屆 spec 被改過造成的原因。

@nobodyzxc

**Comment by rniczh** [comment]
Please refer to the issue #10, Thanks a lot.
