### ISSUE TITLE
STRING and CHARACTER_STRING

### ISSUE THREAD

**Issue by enewen0324** [ICD20/hw1#8]
請問 單引號 的string要跟 雙引號 一起歸類在STRING嗎?
理解上它們是不同的，且在初始flex file中是有CHARACTER_STRING這個類別的。
![image](https://user-images.githubusercontent.com/55022091/93763545-44c5a280-fc44-11ea-92e5-a5508960f8cc.png)

還是說一切以助教的answer file為準?
![image](https://user-images.githubusercontent.com/55022091/93762203-b05a4080-fc41-11ea-9b0f-ca166fd560ce.png)
如果是以助教的answer file為準，是不是所有格式(包含type後面跟的名稱、數字、第幾行、第幾位元......；或是comment的輸出訊息)都要跟助教的版本統一才會算對嗎?

**Comment by rniczh** [comment]
Please refer to the issue #10, thanks a lot
